package sop_corba.ObtenerEstadisticasIntPackage;

/**
* sop_corba/ObtenerEstadisticasIntPackage/estadisticasDTOHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from operaciones.idl
* jueves 8 de junio de 2023 11:42:00 AM COT
*/

public final class estadisticasDTOHolder implements org.omg.CORBA.portable.Streamable
{
  public sop_corba.ObtenerEstadisticasIntPackage.estadisticasDTO value = null;

  public estadisticasDTOHolder ()
  {
  }

  public estadisticasDTOHolder (sop_corba.ObtenerEstadisticasIntPackage.estadisticasDTO initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sop_corba.ObtenerEstadisticasIntPackage.estadisticasDTOHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sop_corba.ObtenerEstadisticasIntPackage.estadisticasDTOHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sop_corba.ObtenerEstadisticasIntPackage.estadisticasDTOHelper.type ();
  }

}
