package sop_corba.ObtenerEstadisticasIntPackage;


/**
* sop_corba/ObtenerEstadisticasIntPackage/estadisticasDTOHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from operaciones.idl
* jueves 8 de junio de 2023 11:42:00 AM COT
*/

abstract public class estadisticasDTOHelper
{
  private static String  _id = "IDL:sop_corba/ObtenerEstadisticasInt/estadisticasDTO:1.0";

  public static void insert (org.omg.CORBA.Any a, sop_corba.ObtenerEstadisticasIntPackage.estadisticasDTO that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static sop_corba.ObtenerEstadisticasIntPackage.estadisticasDTO extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [4];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[0] = new org.omg.CORBA.StructMember (
            "cantidadSolicitudes",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_float);
          _members0[1] = new org.omg.CORBA.StructMember (
            "promedioValorSolicitudes",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_float);
          _members0[2] = new org.omg.CORBA.StructMember (
            "diferenciaMenorSolicitudMayorSolicitud",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_float);
          _members0[3] = new org.omg.CORBA.StructMember (
            "tasaCrecimiento",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (sop_corba.ObtenerEstadisticasIntPackage.estadisticasDTOHelper.id (), "estadisticasDTO", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static sop_corba.ObtenerEstadisticasIntPackage.estadisticasDTO read (org.omg.CORBA.portable.InputStream istream)
  {
    sop_corba.ObtenerEstadisticasIntPackage.estadisticasDTO value = new sop_corba.ObtenerEstadisticasIntPackage.estadisticasDTO ();
    value.cantidadSolicitudes = istream.read_long ();
    value.promedioValorSolicitudes = istream.read_float ();
    value.diferenciaMenorSolicitudMayorSolicitud = istream.read_float ();
    value.tasaCrecimiento = istream.read_float ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, sop_corba.ObtenerEstadisticasIntPackage.estadisticasDTO value)
  {
    ostream.write_long (value.cantidadSolicitudes);
    ostream.write_float (value.promedioValorSolicitudes);
    ostream.write_float (value.diferenciaMenorSolicitudMayorSolicitud);
    ostream.write_float (value.tasaCrecimiento);
  }

}
